[env:heltec_wireless_tracker]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    ; --- Βασικά ---
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    
    ; --- LORA / HELTEC LIBRARY FLAGS (Απαραίτητα για Compilation) ---
    -D REGION_EU868
    -D ACTIVE_REGION=LORAMAC_REGION_EU868
    -D LoRaWAN_DEBUG_LEVEL=0
    -D WIRELESS_TRACKER  ; Λέει στη βιβλιοθήκη ποιο board είναι
    -D HELTEC_BOARD=53   ; ID για Wireless Tracker
    -D SLOW_CLK_TPYE=0   ; Τυπογραφικό της Heltec (TPYE αντί TYPE), πρέπει να μείνει έτσι!
    
    ; --- RADIO PINS ---
    -D RADIO_NSS=8
    -D RADIO_RESET=12
    -D RADIO_DIO1=14
    -D RADIO_BUSY=13
    -D LORA_CLK=9
    -D LORA_MISO=11
    -D LORA_MOSI=10
    
    ; --- DISPLAY FIX (ST7735S 80x160 Mini) ---
    ; Αυτά χρειάζονται για να δουλέψει σωστά η TFT_eSPI
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D TFT_MISO=-1
    -D TFT_MOSI=42
    -D TFT_SCLK=41
    -D TFT_CS=38
    -D TFT_DC=40
    -D TFT_RST=39
    -D TFT_BL=21
    -D ST7735_GREENTAB160x80=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_ON

lib_deps = 
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.1.5
    h2zero/NimBLE-Arduino@^1.4.1
    jgromes/RadioLib @ ^7.5.0
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BME280 Library@^2.3.0
    ./lib/DFRobot_MICS 
